# Generated by Django 3.1.4 on 2020-12-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_buzzed_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_picture_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='room_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
