# Generated by Django 3.1.4 on 2020-12-18 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0002_auto_20201217_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jeopardy.game')),
            ],
        ),
    ]
