# Generated by Django 3.1.4 on 2020-12-18 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0003_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='jeopardy.game'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='jeopardy.team'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='jeopardy.category'),
        ),
        migrations.AlterField(
            model_name='team',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='jeopardy.game'),
        ),
    ]
