# Generated by Django 3.1.4 on 2020-12-20 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0005_auto_20201218_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_buzzed_on',
        ),
    ]
